### ISSUE TITLE
Lag on Linux

### ISSUE THREAD

**Issue by boris-ns** [granttitus/FlappyBird#28]
I tried running this game on Linux(I'm using Linux Mint 18) and there is so much lag.
My advice is to add this line of code in main render method (it works for my games)
`Toolkit.getDefaultToolkit().sync();`

**Comment by MarcusAdriano** [comment]
I solved this issue updating the Thread.sleep(VALUE) where VALUE = 20 instead of 25 in Game class.

**Comment by granttitus** [comment]
Fixed. Thanks for the suggestion.

**Comment by granttitus** [comment]
Commit https://github.com/granttitus/FlappyBird/commit/130462405039fd2e108ad1b9f205d789bdd4402c
